[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "zomba"
authors = [
    {name = "Ji Cheng", email = "jicheng9617@gmail.com"},
]
description = "My package description"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["multi-objective", "bandits"]
license = {text = "BSD-3-Clause"}
classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "requests",
    'importlib-metadata; python_version>"3.9"',
]
dynamic = ["version"]